### ISSUE TITLE
Bug: Emerald TestRPC can't connect to Port: http://127.0.0.1:1920

### ISSUE THREAD

**Issue by YazzyYaz** [ETCDEVTeam/emerald#13]
Info: After installing emerald, I get the following output to show it's installed:
```
✔ sputnikvm-dev: finished installation
✔ emerald-wallet: finished installation
✔ emerald-explorer: finished installation
✔ solc: finished installation
✔ emerald-vault: finished installation
```

It shows emerald-vault as installed. However, when I run `emerald testrpc`, I get the following output:
```
error importing wallets to emerald-vault { FetchError: request to http://127.0.0.1:1920 failed, reason: connect ECONNREFUSED 127.0.0.1:1920
    at ClientRequest.<anonymous> (/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to http://127.0.0.1:1920 failed, reason: connect ECONNREFUSED 127.0.0.1:1920',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```

I believe that even though `emerald-vault` is installed, it's not running first when we run the `emerald testrpc` command. I verified that it would work by manually running `emerald-vault server`, and then running `emerald testrpc`, and I get the following output:
```
imported wallets to emerald-vault
imported wallets to emerald-vault
```

NOTE: This happens both on the v.1.1.0 and v1.0.0 of the wallet.

**Comment by shanejonas** [comment]
you need to run `emerald vault` before `testrpc`. but its not required.

the functionality error'ing is that its trying to be smart and auto import 1 of the keys into vault.

i think we're updating the docs to explicitly say to boot `vault` before `testrpc`.

but yea, need to have some sort of configuration for what i would call 'services', and how they depend on eachother
