### ISSUE TITLE
Bug: Emerald Deploy causes Error with Emerald TestRPC

### ISSUE THREAD

**Issue by YazzyYaz** [ETCDEVTeam/emerald#14]
Info: I was following along this guide: https://docs.etcdevteam.com/emerald-sdk/emeraldsdk-get-started 

I got to the step of running `emerald deploy` while `emerald testrpc` is running in a separate window.
I soon get the error on `emerald testrpc`:

```
imported wallets to emerald-vault
imported wallets to emerald-vault
0x7a07137f0fb29e236dbc214a558f8d5515c5d2594d5d48be2d983dd0825204cd
/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var re

Error: Private key does not satisfy the curve requirements (ie. it is invalid)
    at new Wallet (/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/node_modules/ethereumjs-wallet/index.js:28:11)
    at Function.Wallet.fromPrivateKey (/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/node_modules/ethereumjs-wallet/index.js:203:10)
    at Function.fromPrivateKey (/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/node_modules/emerald-js/lib/wallet.js:71:61)
    at lines.map (/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/index.js:81:34)
    at Array.map (<anonymous>)
    at Socket.<anonymous> (/Users/yazkhoury/.nodenv/versions/8.11.1/lib/node_modules/emerald/index.js:75:27)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
```

NOTE: I'm posting the private key of a testrpc generated, so not too concerned about it being here since I have zero etc or anything on it. 

Also, I did this install using the latest Emerald Wallet v1.1.0 which I've forked into my repo and installed directly from: https://github.com/YazzyYaz/emerald/commit/ebfc582d9fa9f0f2cf5201e039e28ff48c8625ea

So, I don't think it's related to the new wallet version, since I saw the same bug on the previous v.1.0.0 wallet version and I initially assumed it was related to the wallet.

**Comment by YazzyYaz** [comment]
Note: Retested it by importing the private key again but ommitting the 0x at the beginning of the key (which I assumed was the reason for the bug) into Emerald Wallet, and I got the same error on the front end right now 
<img width="416" alt="screen shot 2018-10-26 at 5 00 08 pm" src="https://user-images.githubusercontent.com/9094204/47592474-71ca8700-d941-11e8-8bcf-a1d76f3d75c3.png">

**Comment by shanejonas** [comment]
fixed in this commit: https://github.com/ETCDEVTeam/emerald/commit/451574f1ec6575b8775ae471decf240f73d51f9b

**Comment by Prajan87** [comment]
I am facing the same problem and I have installed emerald recently. Can you give me a solution?
